name: settings
description: "Package for settings management."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ../core
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  bloc_test: ^9.1.7
  json_serializable: ^6.8.0

flutter:
  generate: true
