// Mocks generated by Mockito 5.4.4 from annotations
// in settings/test/features/locales/cubit/locale_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:core/dartz.dart' as _i3;
import 'package:core/errors.dart' as _i6;
import 'package:core/usecases.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:settings/src/domain/repositories/locale_repository_interface.dart'
    as _i2;
import 'package:settings/src/domain/usecases/get_locale.dart' as _i4;
import 'package:settings/src/domain/usecases/save_locale.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeILocaleRepository_0 extends _i1.SmartFake
    implements _i2.ILocaleRepository {
  _FakeILocaleRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetLocale].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocale extends _i1.Mock implements _i4.GetLocale {
  MockGetLocale() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILocaleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILocaleRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILocaleRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>>.value(
            _FakeEither_1<_i6.Failure, _i7.Locale>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>>);
}

/// A class which mocks [SaveLocale].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLocale extends _i1.Mock implements _i9.SaveLocale {
  MockSaveLocale() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILocaleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILocaleRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILocaleRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.Locale? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
