name: business_card_scanner
description: "Business card scanner mobile app made with Flutter."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  core:
    path: packages/core
  settings:
    path: packages/settings
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
