// Mocks generated by Mockito 5.4.4 from annotations
// in settings/test/domain/usecases/get_locale_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:core/dartz.dart' as _i3;
import 'package:core/errors.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:settings/src/data/datasources/local_data_source.dart' as _i2;
import 'package:settings/src/data/repositories/locale_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeISettingsLocalDataSource_0 extends _i1.SmartFake
    implements _i2.ISettingsLocalDataSource {
  _FakeISettingsLocalDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocaleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleRepository extends _i1.Mock implements _i4.LocaleRepository {
  MockLocaleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ISettingsLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeISettingsLocalDataSource_0(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i2.ISettingsLocalDataSource);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>> getLocale() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocale,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>>.value(
            _FakeEither_1<_i6.Failure, _i7.Locale>(
          this,
          Invocation.method(
            #getLocale,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Locale>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> saveLocale(_i7.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocale,
          [locale],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #saveLocale,
            [locale],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
